# Site settings
title: coding_skills << something_new
header-img: img/home-bg.png
email: kyle.kinnear@gmail.com
copyright_name: kylekinnear
description: > # this means to ignore newlines until "baseurl:"
  My journey into the world of programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kylekinnear
learn_profile: kylekinnear
email_username: kyle.kinnear@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
